### ISSUE TITLE
make code formatting consistent accross projects

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#174]
Thanks, @HeinrichFilter for suggesting this.

We should discuss code formatting. Heinrich suggested this:

Things to consider:
- Tab vs Space (E.g. looking at VehicleRoutingProblem.java which mixes tabs and spaces in one file. When viewed in GitHub (which defaults to 8 spaces for a tab) you can see that the formatting is inconsistent.). Recommendation, use 4 spaces
- Line endings. Recommendation, keep it as is: LF
- Character set. Recommendation, keep it as is: UTF-8
- Max line length. Personal preference: >= 120

see also [editorconfig.org](http://editorconfig.org/)

**Comment by oblonski** [comment]
Any other preferences?

**Comment by HeinrichFilter** [comment]
I evaluated a few Code Style including the [Google Java Code Style](https://google.github.io/styleguide/javaguide.html) and some of the build-in styles in Eclipse.

I was looking for a style that would require the least number of changes in the code base to make it "compliant" while ensuring that the main committers are comfortable.

What IDE/editors are most of the committers using?

IDEs can do a lot of formatting but I think adding a `.editorconfig` like the following would be a good starting point:

```
root = true

[*]
indent_style = space
indent_size = 4
insert_final_newline = true
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
max_line_length = 120

[.travis.yml]
indent_size = 2
```

Usually it is the `indent_style` that is debated most. Here are some stats about line changes if the java code base is changed from tabs to spaces (this excludes the XML files):
`358 files changed, 26955 insertions(+), 26955 deletions(-)`

Convert spaces to tabs:
`390 files changed, 19930 insertions(+), 19930 deletions(-)`

That means more lines but fewer files will be touched for a once-off formatting run if the suggested `.editorconfig` file is applied.

I personally prefer spaces because it is the default in IntelliJ and other JetBrains based IDEs but would be comfortable with tabs too.

The big question is whether a once-off formatting run should be done since it messes up the "Blame" history with white-space changes.

I think such a formatting run has more advantage in the long run and I would be willing to do the work if the good people of Jsprit approve :)

**Comment by oblonski** [comment]
The formatting rules are reasonable. I use IntelliJ and what you proposed to start with are my default settings :). Thus changes only happen for xml-files, i.e. pom files as well as example and resource files. Correct?

**Comment by skroll** [comment]
I was just looking at this issue today. I would definitely suggest looking into using checkstyle to identify what files have mismatched code formatting. Also it could be used to verify formatting when accepting pull requests.

**Comment by oblonski** [comment]
@skroll Thanks for your suggestion. I guess you meant [checkstyle](https://github.com/checkstyle/checkstyle)? Also an interesting tool. As far as I can judge it, it checks whether the code complies with Google Code Style rather than that we can define our style and make sure that every IDE is aware of this style.

**Comment by karussell** [comment]
> By default it supports the Google Java Style Guide and Sun Code Conventions, but is highly configurable. 

;)

**Comment by oblonski** [comment]
@karussell Ahh. This sounds even better :).

**Comment by skroll** [comment]
It's really easy to configure. You simply define your rules in the xml file and it will output any errors. There's a maven plugin for it, or else you can just run it manually. Just make sure your .editorconfig matches those rules and you're all set.

You can also enforce the way braces are done, spacing, etc.

I use it to keep the developers (especially contractors) in check at work :)

**Comment by HeinrichFilter** [comment]
I like the idea of using checkstyle. We also use it but mainly through [SonarQube](http://www.sonarqube.org/)

In my mind this is a two step process:
1. Do a once-off reformatting of the code
2. Introduce checkstyle (or similar) into the build process to enforce consistency in the future

@oblonski a once-off reformatting would affect all types of files: Java and XML files (POMs and resources)

I think this discussion might be easier when looking at actual code. Have a look at the Pull Request and let me know what you think.

The main formatting changes are:
- Tabs converted to spaces
- Adding a space after `if`, `for`, method parameters, string concatenation `+`, casts etc.
- Deleting trailing whitespace
- Addeding `<p>` into java docs to make them more readable when rendered.


The following is a quick example that shows the whitespace characters. The pull request changes the code from this:
<img width="609" alt="Pre formatting" src="https://cloud.githubusercontent.com/assets/265415/9516216/7002ec7a-4ca7-11e5-8d4f-85346c348bfa.png">

To this:
<img width="620" alt="screenshot 2015-08-27 10 27 20" src="https://cloud.githubusercontent.com/assets/265415/9516237/99d04b74-4ca7-11e5-8799-435c98ff252f.png">

**Comment by oblonski** [comment]
Thanks, @HeinrichFilter for your suggestion :+1:

**Comment by oblonski** [comment]
and thanks also to @skroll for suggesting checkstyle in addition to .editorconfig

**Comment by oblonski** [comment]
I`d prefer to switch to this:
https://github.com/graphhopper/graphhopper/issues/770#issuecomment-246490515
thus make IntelliJ default format the default format
