### ISSUE TITLE
change licence to apache v2

### ISSUE THREAD

**Issue by oblonski** [graphhopper/jsprit#216]

**Comment by GabrielGreslin** [comment]
Hello !
Why moving from LGPL to apache v2 ?

**Comment by oblonski** [comment]
We want to make it even more attractive for any use case. This way users have much more freedom to use and modify jsprit, and hopefully they will contribute their modifications back (but dont actually need to). This freedom might be a better ground for innovations? 
Do you have doubts?

**Comment by GabrielGreslin** [comment]
Yes, i have doubt about the part "they will contribute their modifications back". This would allow more commercial use, so more secrets to keep. Thanks for answering anyway, you're surely right !

**Comment by oblonski** [comment]
@karussell What do you think? Did I miss an important reason for switching license?

**Comment by oblonski** [comment]
Lets assume we improve jsprit fast then keeping the secrets also means a lot of integration work (if you always want to use the latest release). This might be an incentive to contribute back.

**Comment by karussell** [comment]
What we observed with LGPL (not only with jsprit) is that bigger players are hesitating to use it (due to the strict copyleft) and smaller players just modify jsprit and use this in their project without making the modifications public. And in case of jsprit it is even more complex: jsprit is "too customizable" :) ... of course that is intended and very good, but this allows changes to the core without violating the LGPL. 

Also how would we ever know that they use jsprit and could enforce the license? The truth is: we won't ever know and cannot force people to contribute this back. Even with AGPL or something we need to trust people to being fair or big enough to care about licensing.

*With Apache this is easy: everyone can just do what they want with it.*

This reason, I think, is key for a vital open source project. Bigger companies can just use it and e.g. decide months or years later to contribute (parts) back.

> Lets assume we improve jsprit fast then keeping the secrets also means a lot of integration 
> work (if you always want to use the latest release). This might be an incentive to contribute back.

That is a very good point to increase contribution!

**Comment by GabrielGreslin** [comment]
> Bigger companies can just use it and e.g. decide months or years later to contribute (parts) back

I see, you're more on a mid-long term point of view. I agree !

**Comment by oblonski** [comment]
from now on it is Apache License v2
