### ISSUE TITLE
Changing CostPerDistance affecting optimal output

### ISSUE THREAD

**Issue by anurag1paul** [graphhopper/jsprit#232]
I have been using Jsprit for solving a capacitated vehicle routing problem with time windows and heterogeneous vehicles. I kept all other factors constant and just changed costPerDistance (same for all vehicles) and checked to see if optimal solution remains constant.

My observations are: 

- costPerDistance: 1 Optimal Distance: 1158	number of vehicles: 12
- costPerDistance: 5 Optimal Distance: 1171	number of vehicles: 13
- costPerDistance: 10 Optimal Distance: 1111 number of vehicles: 13
- costPerDistance: 100 Optimal Distance: 1158 number of vehicles: 13
- costPerDistance: 1000 Optimal Distance: 1106 number of vehicles: 13

I expected that by changing costPerDistance, only total costs would change, but the optimal solution would remain same. But, this didn't happen. Could someone please explain the reason for this variation?

**Comment by oblonski** [comment]
Thanks. What are your observations exactly? I do not understand it yet. Could you give some more details?

**Comment by oblonski** [comment]
Ahh now I see

**Comment by anurag1paul** [comment]
I don't understand why optimal distance varies non-monotonically with an increase in costPerDistance.

**Comment by oblonski** [comment]
I assume that this is because random variations. jsprit uses random numbers in different parts of the algorithm, e.g. selectiing a ruin strategy etc.. If you calc exactly the same problem, it should produce the same result. However, the problem changes if cost per distance is increased (does it really change the problem? hmm). Can you make your analysis again with different seeds of the random number generation. Lets calc 10 times with cost_per_distance = 1 and use diff. seed, average the results and do it for cost_per_distance = 10. If there is still this obversation, we need to investigate further. You can define a RNG like this:

```
RandomNumberGeneration.setSeed(4711);
RandomNumberGeneration.getRandom();
```

And then you can set it like this
```
Jsprit.Builder builder = Jsprit.Builder.newInstance(vrp);
builder.setRandom(random);
```

**Comment by anurag1paul** [comment]
Hi Stefan,

I performed the analysis and found averages for optimal distance as 1132 and 1130 for costPerDistance as 1 and 10 respectively. So, I guess the issue is due to random numbers and not due to algorithm

**Comment by oblonski** [comment]
:+1:

**Comment by oblonski** [comment]
@anurag1paul Can I close this?

**Comment by anurag1paul** [comment]
Yeah,  thanks for your help.
