### ISSUE TITLE
JobInsertionConsideringFixCostsCalculator with shipments bug

### ISSUE THREAD

**Issue by PGWelch** [graphhopper/jsprit#286]
Hi, 

I've come across a bug in the v1.6.2 version of jsprit being used in ODL Studio but as far as I can tell, the bug should still hold in the latest jsprit. Apologies for the lack of unit test case, but the bug should be relatively obvious. In JobInsertionConsideringFixCostsCalculator you have the method getFixCostContribution which calls getDeltaAbsoluteFixCost and getDeltaRelativeFixCost. These methods estimate the fullness of the route based on capacities and then return a proportion of the fixed cost based on how full the route is. If they think the job can't fit into a route, they return Double.MAX_VALUE, giving ~Double.MAX_VALUE insertion costs.

The fullness test doesn't work for shipments though, as it just adds the job quantity to the current MAXLOAD in route. e.g. we have vehicle capacity 1, and shipments (A->B) and (C->D) both with quantity 1. A valid route is therefore A, B, C, D but not A, C, B , D. Once (A->B) is loaded onto the route you get a Double.MAX_VALUE insertion cost for (C->D), as the test for fullness is incorrect and thinks (C->D) can't be inserted into the route, when in-fact it can. Does this make sense?

The upshot is that if you have 10 shipments all with quantity 1, and 10 vehicles all with capacity 1, all 10 vehicles will be used irrespective of the vehicle fixed cost because the job insertion cost on pre-existing routes is wrong. However if you set just 1 vehicle to be available, and other constraints like time windows do not apply, all 10 shipments could fit on 1 vehicle (at a lower total cost assuming vehicle fixed cost is high).

I'm guessing the same issue would apply when you have mixed collections and deliveries in a route.

**Comment by oblonski** [comment]
thanks @PGWelch ... I will look into this asap

**Comment by cpalanzo** [comment]
Any estimate on when this might be corrected? We are trialing a shipment solution that is running into this problem.

**Comment by PGWelch** [comment]
The easiest solution may be to make the dependence on capacities optional and turned off by default? Afterall VRPs are generally either capacity constrained OR available working time constrained? Discounting the fixed vehicle cost based on the fraction of solution loaded seems sensible though, in my opinion (providing a fixed cost is never discounted to zero)

**Comment by oblonski** [comment]
Trying to reproduce this the next days. If I did this, it should be easy and fast to fix.

**Comment by oblonski** [comment]
Ok. I now know what you mean. First, we can ensure that both relFixedCost and absFixedCost will never be Double.MAX_VALUE since this calc has no responsibility to check capacity constraints (which is done elsewhere). The calculation of absFixedCost seems then reasonable as it is. 
However, the calculation of relFixedCost which is basically 
(usedCapacity+newShipment.size)/totalCapacity(newVehicle) - usedCapacity/totalCapacity(currentVehicle)*fixedCosts(currentVehicle)
is more complicated when having Shipments (as you pointed out correctly). The difficulty is that we do not know totalCapacity(newVehicle) or better available capacity since "available capacity" is actually an expectation of how much capacity will be utililized when all shipments are assigned. Here are some relations which might help in our new approach:

1. The available capacity increases with the capacity of the vehicle
2. The available capacity increases with the remaining operation time of the vehicle
3. The available capacity increases with large time window of pickup and deliverShipment
4. marginal relative fixed costs should always be smaller than marginal absolute fixed costs
5. marginal relative fixed costs should always be greater than zero
6. marginal relative fixed costs should be somehow dependent on shipment.size

@PGWelch Any further idea?

**Comment by oblonski** [comment]
With the link above we can also discuss this in code.

**Comment by PGWelch** [comment]
@oblonski I'm not sure I understand the rationale behind the relative fixed cost equation 100% (or if I did understand at one point, I've subsequently forgotten!). As I understand it, roughly speaking the relative fixed cost should increase the more 'full' a vehicle is, so when vehicles are not very full - and you're likely to use a new vehicle in the future anyway - new vehicles are cheaper? 

If so, I can't really see this logic (the relative fixed cost) working well in-practice, as there are many different ways a vehicle can be 'full', as you've listed above. Problems could be work time constrained (i.e. not really using capacities), capacity constrained, a mixture of both, or even constrained by some additional user-defined constraint.

Also as the purpose is to guide the insertion heuristic into saving - or not saving - a vehicle depending on how many jobs remain to be inserted and the vehicle's fixed cost, I'm not sure its even correct to think about the degree of fullness of a vehicle? The fixed cost either applies or doesn't if the vehicle is non-empty or empty - i.e. its a binary thing?

Anyway, I would tentatively recommend just dropping the relative fixed cost and only using the absolute cost - which is multiplied by either solutionCompletenessRatio or the square of solutionCompletenessRatio ? There may be specific problems where this yields worse results but (in my opinion) its more likely to be robust over a wider range of problems?

**Comment by oblonski** [comment]
Ok. I fear that I need to leave fix costs contribution which adds up to the insertion costs to the user. I will keep the increasing absolute fixed costs (increasing with the number of unassigned jobs left), but remove the relative fixed costs part which is dependent on future expectations about occupancy rate and thus future expectations about fixed unit costs. This, in turn, is dependent on whether the problem is capacity bound or working time bound - as Phil wrote correctly.

**Comment by oblonski** [comment]
If `.setProperty(Jsprit.Parameter.FIXED_COST_PARAM,"0.5")` is set, it adds [this](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/IncreasingAbsoluteFixedCosts.java) by default, i.e. increasing absolute fixed costs. If you want to have the exact same behaviour as before (without the above bug), you need to add [DecreasingRelativeFixedCosts](https://github.com/graphhopper/jsprit/blob/master/jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/DecreasingRelativeFixedCosts.java) as well as follows:

```
StateManager stateManager = new StateManager(vrp);
ConstraintManager constraintManager = new ConstraintManager(vrp,stateManager);

DecreasingRelativeFixedCosts decreasingRelativeFixedCosts = new DecreasingRelativeFixedCosts(stateManager,vrp.getJobs().size());
constraintManager.addConstraint(decreasingRelativeFixedCosts);

VehicleRoutingAlgorithm vra = Jsprit.Builder.newInstance(vrp)
   .setProperty(Jsprit.Parameter.FIXED_COST_PARAM,"0.5")
   .setStateAndConstraintManager(stateManager,constraintManager)
   .buildAlgorithm();

//you need to add this here as well due to calculating solution completeness ratio
vra.addListener(decreasingRelativeFixedCosts);
```

**Comment by PGWelch** [comment]
Thanks for the fix - that's great.

**Comment by cpalanzo** [comment]
Phil, 
Does this impact our trial? Do I have to wait for you to update the AWS server?
Charlie -----------------------------------------------------------------------------------------------------------  "The faster you react, the less you think. Not always, but often." - Jason Fried

**Comment by PGWelch** [comment]
@cpalanzo This doesn't affect ODL Live, only ODL Studio. ODL Live has replaced a lot of the base jsprit code including the code causing this bug; ODL Studio just uses the standard version of jsprit.
