### ISSUE TITLE
New feature request - custom properties

### ISSUE THREAD

**Issue by grantm009** [graphhopper/jsprit#347]
Hi

Could you please consider adding a custom properties property to pickups/deliveries/vehicles/drivers/locations etc.

IE job.setCustomProperties and job.getCustomProperties
Location.setCustomProperties and Location.getCustomProperties

This could be as simple as a String that a value can be stored in or a list that a list of values could be stored. The string would be easiest to implement and the programmer could store the values as a JSON string in the string field.

This would be very useful in constraints as well as across the whole object suite.

An example of how we could use this would be "depot=true" on some pickups and deliveries where we need to know if the location is a depot when making a decision in a constraint.

By making it a string the programmer can keep anything in there.

Does this make sense ?

regards
Grant

**Comment by balage1551** [comment]
Almost agree, but the properties should be a Map<String,Object>, instead of Map<String,String> to avoid unnecessary, repeated string parsing and it may offer some typed getters (getAsObject, getAsString, getAsInt, getAsBoolean, etc) which may throw exception in case of incompatible class cast, to keep the main code clean.

Alternatively -- and maybe even more preferably -- I propose to use a single Object type `userData` field to contain the info. It would let the user to assign any type of data object with exactly the fields it needs. Its safer and cleaner then untyped maps. If the getter of user data is made generic, a single unsafe cast is enough to handle type. _(Sidenote: Using generic in class would be a bad idea, because it would be tiresome to bring through whole the code and the type info would be lost anyway within engine code)._

**Comment by jsroyal** [comment]
Thanks, @grantm009 It is good features to add.
I'm also looking for that how to add custom properties. 
since 25 days I'm working on it capacitive and time window constraint VRP.

**Comment by grantm009** [comment]
Thanks for the support Balage and jsroyal. I agree a map would be the best approach.

kind regards
Grant

**Comment by oblonski** [comment]
Thanks for suggesting this. I assume it should be straightforward to add such a possibility. 
@balage1551 What do you think is the most appropriate approach for this? I understand that there are two reasonable options: Map<String,Object> and 

> a single Object type userDate

Can you elaborate more on the latter? Or even make a concrete suggestion via PR?

.

**Comment by balage1551** [comment]
Well, to be honest, I can't give any strong reasons for the Map implementation. Some minor pro reasons are that the user don't have to create new class and the easier to print it Uniformly. 
The values, including the keys are private to the user implementation,  so Jsprit don't and shouldn't  make any use of it. 
The single object approach has some nice benefits :
* more flexible: could contain any class, from as simple as a primitive Wrapper to a complex class. 
* the first option is really a special case of the general one: by assigning a Map as user data. 
* the class assigned could be a pure data class, but also could encapsulate partial or complete business logic. 

As a conclusion, I propose the user data approach. 

Implementation is easy and straightforward, so I suggest to add it to both the current and the new version. In new version, both job and activity should have a user data field. 

(I'm on holiday today, so I will be online in the evening.)

**Comment by grantm009** [comment]
Could I plead the case for Location  and other objects to also have a user data field.
This is important (to me at least) for classifying locations. For example a hard constraint preventing a pickup from a location mid route if the location type is "depot" but allowing it if the location is type "customer". 

I think this capability, if deployed broadly across objects, really enhances the constraints models for skills and attributes. For example if a Location has a userData of "SecureSite" T/F then the driver can also have this SecureSite tag as well as the driver and maybe even the entire route. So that in a multi vehicle problem will **only** route secure vehicles to secure sites and not non-secure sites. 

I hope Im not waffling too much.

regards
Grant

**Comment by balage1551** [comment]
Well, your request is right. If we add this new feature (which is as simple as to add a new field to the classes and to their builders, at least in most of the cases), we should do it as widly as we can. 

I propose to add the userData field to
* Job
* Activity (in new version only)
* Vehicle
* Vehicle type
* Location (as a fluent api setter, because it has no builder, only several factory methods)

What do you think, @oblonski ? (I could do it quickly for the current version, so the feature may be available for the users within a week.)

**Comment by oblonski** [comment]
I am still not 100 percent sure whether we really need this. Cant the user just enhance e.g. a vehicle with a custom wrapper? Where do you see the advantage of user defined data field over a wrapper? I see one pro: it is slightly less effort.

**Comment by balage1551** [comment]
I have several pros: :-P

It is some kind of information composition. And as Gamma stated (design patterns): _prefer composition over inheritence_. ;-) With inheritence, when the user has to deal with different set of user data for different jobs/vehicles, he would either make the composition himself or would have to create several subclasses.

Another inconvience the extended version would cause is that in any place where the user has to deal with an object received from the API, should check type and cast the object manually before even accessing this field. (Although, this cast can't be avoided by the user data version, neither.)

Another reason is, because we use builders for constructing most of these objects, to extend them, one has to extend the builder as well. This is an uncomfortable overhead and in case of deserialization (reading objects from config file), the support would be broken as well. (Or we should provide factory injection to these readers.)

This pattern is widely used in API-s to allow users to attach domain specific information to the objects without the need to extend the class. 

The less of effort taken to implement this feature (which is really only a new field/getter/setter block) doesn't prove the amount of work placed on the end users if we force them to do this.

**Comment by oblonski** [comment]
👍 Convinced :). Thanks a lot.

**Comment by balage1551** [comment]
Should I do it? I can do it tomorrow evening.

**Comment by oblonski** [comment]
Yes, this would be great.

**Comment by grantm009** [comment]
Yes indeed it would be really great. 
Thanks for the fast consideration. 
You guys rock.

**Comment by grantm009** [comment]
You probably need someone to help test it. 
Pick me !!! :)

**Comment by grantm009** [comment]
Hi @balage1551 
Im not a GitHub man. What linux command would I used to pull down your committed code ?
regards
Grant

**Comment by jsroyal** [comment]
@grantm009 If you have cloned this repo then just used `git pull origin master`
Let me know if other cases.

**Comment by oblonski** [comment]
see latest release: https://github.com/graphhopper/jsprit/blob/master/WHATS_NEW.md
